version = 2
outputDirectory = "public"

[[headers]]
source = "/i/(.*)"
headers = [
    { key = "Cache-Control", value = "public, max-age=31536000, s-maxage=31536000, immutable" },
]

[[headers]]
source = "/s/(.*)"
headers = [
    { key = "Cache-Control", value = "public, max-age=31536000, s-maxage=31536000, immutable" },
]

[[headers]]
source = "/registry.json"

[[headers.headers]]
key = "Cache-Control"
value = "public, max-age=0, s-maxage=60, stale-while-revalidate=600, stale-if-error=86400"

[[headers]]
source = "/v1/(.*)"

[[headers.headers]]
key = "Cache-Control"
value = "public, max-age=0, s-maxage=60, stale-while-revalidate=600, stale-if-error=86400"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-unknown-linux-gnu.json"
destination = "/i/fe1816b4c42ef81352eedd31df97c99d.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-unknown-linux-musl.json"
destination = "/i/cd2cc1e7d77cf0944fbed1ba2c335305.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-unknown-linux-gnu.json"
destination = "/i/7c4201a101073a36aa18b4b7e1e59f27.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-unknown-linux-musl.json"
destination = "/i/97165bc2665c0a183c5c422443e5e135.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-apple-darwin.json"
destination = "/i/dff5b2754df44369fa9d04a9befc8b72.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-apple-darwin.json"
destination = "/i/f294f0ae6a325c1e70d58c2a6b3de1d7.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-pc-windows-msvc.json"
destination = "/i/306c01a635dccd0df7cf9efd6cacc049.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-pc-windows-msvc.json"
destination = "/i/14e007d1d1429e73f3f20e812ce74213.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-unknown-linux-gnu.testing.json"
destination = "/i/e4b0249ef45f8eaba1a1690277df9be6.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-unknown-linux-musl.testing.json"
destination = "/i/cfbf6846e75721f1c19f80b8494652fc.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-unknown-linux-gnu.testing.json"
destination = "/i/56042742fe6e3de0c9d5d33123daa4de.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-unknown-linux-musl.testing.json"
destination = "/i/e41828eccb78e1c31540a5dce226eb1d.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-apple-darwin.testing.json"
destination = "/i/476daa87d2bb525d957d8ba4d9d9df25.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-apple-darwin.testing.json"
destination = "/i/7f3ce8ecfbf4993046add5e140a71b43.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-pc-windows-msvc.testing.json"
destination = "/i/e9b2b15fb7f25e1bf2abfe87546ea9d6.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-unknown-linux-gnu.nightly.json"
destination = "/i/94606b80cbd87107f69154d75aae3ee4.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-unknown-linux-musl.nightly.json"
destination = "/i/831b2e1f8a8a898286e3b4ca52457ee6.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-unknown-linux-gnu.nightly.json"
destination = "/i/062275b073ccb9928b17b5e705eb1911.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-unknown-linux-musl.nightly.json"
destination = "/i/43edc1e6a0ad22593d9535aacd098226.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-apple-darwin.nightly.json"
destination = "/i/80b07c239f3d2a75cb76b8132cb0b7b9.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-apple-darwin.nightly.json"
destination = "/i/44004d0d69e73ceb73a98dc9bc61bcfe.json"

[[rewrites]]
source = "/archive/.jsonindexes/x86_64-pc-windows-msvc.nightly.json"
destination = "/i/cdfc57544b10b828d2831e77ca3930a1.json"

[[rewrites]]
source = "/archive/.jsonindexes/aarch64-pc-windows-msvc.nightly.json"
destination = "/i/53669408a953d4843b5f409b90ceaaaa.json"
