"""Re-deriving every generated byte without touching the network.

`validate` is the check a reviewer and CI both run. It reads only what is
committed, re-derives the bootstrap indexes, the snapshot trees, the schemas
and the two moving documents, and compares them byte-for-byte with what the
repository claims. It must never reach the network to do it: the whole point is
that the published tree is a function of the evidence in the repository.
"""

from __future__ import annotations

import shutil
import socket
from collections.abc import Callable
from pathlib import Path

import pytest
from support import complete_repository, copy_release

from gel_registry import __main__ as cli
from gel_registry.contracts import Pointer, ReleaseRecord
from gel_registry.digest import blob_id, canonical_json
from gel_registry.validation import (
    ValidationReport,
    validate_capture_local,
    validate_local,
)

EVERY_LAYER = {
    "capture.manifest",
    "capture.bodies",
    "bootstrap.schema",
    "release.schema",
    "normalization.drift",
    "schema.validity",
    "render.drift",
    "pointer.integrity",
    "snapshot.listing",
    "snapshot.internals",
    "moving.root",
    "publication.blob_store",
}
CAPTURE_ONLY = {
    "capture.manifest",
    "capture.bodies",
    "bootstrap.schema",
    "normalization.drift",
}


def test_local_validation_is_offline_and_checks_every_layer(
    tmp_path: Path,
    package_index_data: dict[str, object],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    release = copy_release(tmp_path)
    release.write_bytes(
        canonical_json(ReleaseRecord.model_validate_json(release.read_bytes()))
    )
    complete_repository(tmp_path, package_index_data)

    def fail_socket(*_args: object, **_kwargs: object) -> object:
        raise AssertionError("local validation attempted a network connection")

    monkeypatch.setattr(socket, "socket", fail_socket)

    report = validate_local(tmp_path)

    assert isinstance(report, ValidationReport)
    assert report.ok, report.errors
    assert EVERY_LAYER.issubset(report.checks)

    assert cli.main(["validate", "--repo", str(tmp_path)]) == 0
    assert capsys.readouterr().out == "ok\n"


def test_release_records_use_their_source_identity_path(
    tmp_path: Path, package_index_data: dict[str, object]
) -> None:
    """A release path names the source owner, repository, and release ID."""
    release = copy_release(tmp_path)

    assert release.relative_to(tmp_path) == Path(
        "releases/gelstable/gel-cli/100.json"
    )

    complete_repository(tmp_path, package_index_data)
    report = validate_local(tmp_path)

    assert report.ok, report.errors


def test_validation_rejects_a_release_path_that_disagrees_with_its_source(
    tmp_path: Path, package_index_data: dict[str, object]
) -> None:
    """The directory names cannot claim a different GitHub source."""
    release = copy_release(tmp_path)
    complete_repository(tmp_path, package_index_data)
    wrong_path = tmp_path / "releases" / "other-owner" / "gel-cli" / "100.json"
    wrong_path.parent.mkdir(parents=True)
    release.rename(wrong_path)

    report = validate_local(tmp_path)

    assert any(
        "release record path does not match its source" in error
        for error in report.errors
    )


def test_local_validation_names_the_immutable_input_that_changed(
    tmp_path: Path, package_index_data: dict[str, object]
) -> None:
    complete_repository(tmp_path, package_index_data)
    base = tmp_path.parent / "base"
    shutil.copytree(tmp_path, base)
    body = tmp_path / "bootstrap" / "stable-x86_64-unknown-linux-gnu.json"
    body.write_bytes(body.read_bytes() + b"\n")

    report = validate_local(tmp_path, base)

    assert not report.ok
    assert any(
        "bootstrap/stable-x86_64-unknown-linux-gnu.json" in error
        for error in report.errors
    )


def test_capture_validation_does_not_require_publication_state(
    tmp_path: Path, package_index_data: dict[str, object]
) -> None:
    complete_repository(tmp_path, package_index_data)
    shutil.rmtree(tmp_path / "public")
    shutil.rmtree(tmp_path / "pointers")

    report = validate_capture_local(tmp_path)

    assert report.ok, report.errors
    assert CAPTURE_ONLY.issubset(report.checks)
    assert not {"pointer.integrity", "render.drift"} & set(report.checks)


def _repoint_at_an_uninstalled_snapshot(repo: Path) -> None:
    (repo / "pointers" / "latest.json").write_bytes(
        canonical_json(Pointer(snapshot="0" * 16))
    )


def _add_an_unexpected_public_path(repo: Path) -> None:
    (repo / "public" / "unexpected.txt").write_bytes(b"unexpected")


def _blob(repo: Path) -> Path:
    return next((repo / "public" / "i").glob("*.json"))


def _corrupt_an_index_blob(repo: Path) -> None:
    """Rewrite a blob so its bytes no longer hash to the name it is filed under."""

    blob = _blob(repo)
    blob.write_bytes(blob.read_bytes().replace(b'"packages"', b'"packages" ', 1))


def _orphan_an_index_blob(repo: Path) -> None:
    """File a well-formed blob no snapshot manifest references."""

    data = b'{\n  "packages": []\n}\n'
    (repo / "public" / "i" / f"{blob_id(data)}.json").write_bytes(data)


def _delete_a_referenced_blob(repo: Path) -> None:
    _blob(repo).unlink()


@pytest.mark.parametrize(
    ("tamper", "expected"),
    [
        pytest.param(
            _repoint_at_an_uninstalled_snapshot,
            ("pointers/latest.json", "public/registry.json"),
            id="pointer-and-moving-documents-are-one-pair",
        ),
        pytest.param(
            _add_an_unexpected_public_path,
            ("public/unexpected.txt",),
            id="unexpected-published-path",
        ),
        pytest.param(
            _corrupt_an_index_blob,
            ("publication.blob_store", "content address"),
            id="blob-does-not-match-its-content-address",
        ),
        pytest.param(
            _orphan_an_index_blob,
            ("publication.blob_store", "not referenced by any snapshot"),
            id="orphaned-blob",
        ),
        pytest.param(
            _delete_a_referenced_blob,
            ("publication.blob_store", "is missing"),
            id="missing-referenced-blob",
        ),
    ],
)
def test_local_validation_rejects_any_deviation_in_the_published_tree(
    tmp_path: Path,
    package_index_data: dict[str, object],
    tamper: Callable[[Path], None],
    expected: tuple[str, ...],
) -> None:
    complete_repository(tmp_path, package_index_data)
    tamper(tmp_path)

    report = validate_local(tmp_path)

    assert not report.ok
    for path in expected:
        assert any(path in error for error in report.errors), report.errors
