"""Narrow, deterministic contracts and operations for legacy artifact rescue."""

from .indexes import (
    RESCUE_ORIGIN,
    RescueCaptureManifest,
    capture_rescue_indexes,
    rescue_capture_root,
)
from .manifests import (
    MANIFEST_NAME,
    build_release_manifest,
    release_manifest_bytes,
    release_manifest_digest,
)
from .models import (
    RescueAbsentIndex,
    RescueAsset,
    RescueIndexCapture,
    RescuePlan,
    RescueRelease,
)
from .operations import (
    DESTINATION_REPOSITORIES,
    AssetOutcome,
    ManifestOutcome,
    PreflightReport,
    ReleaseOutcome,
    RescueManualCleanupError,
    RescuePreflightError,
    RescuePublishError,
    describe_operations,
    execute,
    load_plan,
    preflight,
    publish_plan,
)
from .selection import (
    GitHubTagSource,
    GitTagSource,
    Product,
    TagSource,
    UpstreamTag,
    artifact_name,
    plan_rescue,
)
from .transfer import (
    RescueSourceIntegrityError,
    RescueTransferError,
    RescueUploadIntegrityError,
    transfer_asset,
    transfer_original_asset,
    verify_uploaded_asset,
)

__all__ = [
    "DESTINATION_REPOSITORIES",
    "AssetOutcome",
    "GitHubTagSource",
    "GitTagSource",
    "MANIFEST_NAME",
    "ManifestOutcome",
    "PreflightReport",
    "Product",
    "RESCUE_ORIGIN",
    "ReleaseOutcome",
    "RescueAbsentIndex",
    "RescueAsset",
    "RescueCaptureManifest",
    "RescueIndexCapture",
    "RescueManualCleanupError",
    "RescuePlan",
    "RescuePreflightError",
    "RescuePublishError",
    "RescueRelease",
    "RescueSourceIntegrityError",
    "RescueTransferError",
    "RescueUploadIntegrityError",
    "TagSource",
    "UpstreamTag",
    "artifact_name",
    "build_release_manifest",
    "capture_rescue_indexes",
    "describe_operations",
    "execute",
    "load_plan",
    "plan_rescue",
    "preflight",
    "publish_plan",
    "release_manifest_bytes",
    "release_manifest_digest",
    "rescue_capture_root",
    "transfer_asset",
    "transfer_original_asset",
    "verify_uploaded_asset",
]
